### ISSUE TITLE
Pass down prometheus scraping information in the config context

### ISSUE THREAD

**Issue by MrFreezeex** [FlxPeters/netbox-plugin-prometheus-sd#120]
Hello,

We would like to use this plugin in some kind of "self service manner" netbox wise. Meaning that we would essentially use one http_sd_config (technically two for vms and server in our case) with something like: `/api/plugins/prometheus-sd/devices/?tags=prom-autoconfig` and then use config context to configure metrics_path, ports etc.

The idea is to have something similar as what we used to configure Kubernetes (essentially before or if prometheus-operator is not used) with annotation on pods like: `prometheus.io/scheme`, `prometheus.io/path`, `prometheus.io/port`.

I propose to put something like that in the config context:
```yaml
prometheus-plugin-prometheus-sd:
  - metrics_path: /not/metrics
    port: 4242
    scheme: https
  - port: 4243
```

And then the plugin would discover this and use it for the http sd json essentially. Of course I am happy to work on the implementation, in case that's something that could be included!
