### ISSUE TITLE
Single endpoint with union of devices and virtual-machines?

### ISSUE THREAD

**Issue by candlerb** [FlxPeters/netbox-plugin-prometheus-sd#62]
How hard would it be to make a single endpoint which exposes both devices and virtual-machines?

Reason: AFAICS, currently every Prometheus scrape job needs to be duplicated, since prometheus http-sd can only scrape a single URL.  If you've got a lot of rewriting rules, that can be painful.

A union endpoint would solve this, and `__meta_netbox_model` can be used to distinguish between the objects if necessary.

However, I can see there is much Django ORM queryset and serializer magic going on, so it may not be easy. Maybe [this](https://www.djangosnippets.org/snippets/1933/) is relevant.

**Comment by FlxPeters** [comment]
At the moment this plugin is build as a simple new view to the existing netbox api, but i understand the issue.
My solution is the described duplicate scrape job.

If you have time for this feel free to start an PR. I would love to have the feature my self.

**Comment by candlerb** [comment]
I realised you should be able to put multiple http_sd_configs under the same job:

```
- job_name: netbox
  http_sd_configs:
    - url: https://netbox.example.com/api/plugins/prometheus-sd/devices/
      refresh_interval: 10m
      authorization:
        type: Token
        credentials: 0123456789abcdef0123456789abcdef01234567
    - url: https://netbox.example.com/api/plugins/prometheus-sd/virtual-machines/
      refresh_interval: 10m
      authorization:
        type: Token
        credentials: 0123456789abcdef0123456789abcdef01234567
```

So whilst there is duplication of the credentials, there's little other reason for a combined endpoint.
