### ISSUE TITLE
Prometheus Reader failure

### ISSUE THREAD

**Issue by ekrichbaum** [FlxPeters/netbox-plugin-prometheus-sd#96]
Before I start, thank you for this work and I fully admit this could be me.  No experience with Prometheus at all here.
prometheus-2.42.0.linux-amd64
netbox 3.4.5

API seems to return good data, validly formatted. Ran output through json lint and looks valid.  All elements are strings excep for the id.

```
          "__meta_netbox_id": 81,
```

Prometheus never shows the target at all and logs this error:
```
Feb 23 08:35:13 prometheus.netfortris.com prometheus[11055]: ts=2023-02-23T16:35:13.317Z caller=refresh.go:99 level=error component="discovery manager scrape" discovery=http config=http_sd_devices msg="Unable to refresh target groups" err="json: cannot unmarshal number into Go struct field .labels of type model.LabelValue"
```

Prometheus config:
```
  - job_name: "http_sd_devices"
#    metrics_path: /netbox
    scheme: https
#    static_configs:
#      - targets: ["localhost:9090"]
    http_sd_configs:
    - url: https://netbox.netfortris.net/api/plugins/prometheus-sd/devices/?has_primary_ip=true&name=atl-bdr1
      refresh_interval: 15s
      authorization:
        type: "Token"
        credentials: "blahblahblahforthelength of the token."
```

Validated with curl that the data is returned properly from the url with the proper api key. I get different issues if I try to use the metrics_path so I let it default with the other job into /metrics.
