### ISSUE TITLE
Intended use / Add more usage examples

### ISSUE THREAD

**Issue by ekrichbaum** [FlxPeters/netbox-plugin-prometheus-sd#97]
I can't seem to wrap my head around how this works in general.   Netbox api call (with slight mod to change id to string from other thread) returns a boatload of items out of my netbox.

Those 758 objects all show as "down" because prometheus then tries to contact each of them on port 80 (of which most do not respond).  I assume that I should be adding something to the netbox side so that prometheus then knows what to look for in an object? i.e. use snmp, snmp community, address to use instead of the name?

**Comment by FlxPeters** [comment]
Here is an example how you can use it with `node-exporter`for example.
You have to set the proper port on the `__address__`  label. In this example this is hard coded, but could also be fetched from a regex. 

```
- job_name: node_exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_netbox_services]
    separator: ;
    regex: .*(node-exporter|node_exporter).*
    replacement: $1
    action: keep
  - source_labels: [__address__]
    separator: ;
    regex: ([^:]+)(:[0-9]+)?
    target_label: __address__
    replacement: ${1}:9100
    action: replace
```
